function Convert-ToStandaloneScript {
    <#
    .SYNOPSIS
        Converts a PowerShell script that depends on Import-Module into a standalone script.

    .DESCRIPTION
        Reads the given script, finds all Import-Module statements that reference local
        .psm1/.psd1 module files, extracts the exported functions from those modules,
        and produces a new script that inlines those functions — removing the need to
        have the module installed on the target system.

        Import-Module statements for system/installed modules (referenced by name only,
        without a file path) are left unchanged unless the module can be located via
        Get-Module -ListAvailable.

    .PARAMETER Path
        Path to the source PowerShell script (.ps1).

    .PARAMETER OutputPath
        Destination path for the standalone script. If omitted, writes to
        <SourceBaseName>.standalone.ps1 in the same directory as the source script.

    .PARAMETER Force
        Overwrite the output file if it already exists.

    .EXAMPLE
        Convert-ToStandaloneScript -Path ./MyScript.ps1

    .EXAMPLE
        Convert-ToStandaloneScript -Path ./MyScript.ps1 -OutputPath ./MyScript.dist.ps1 -Force
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [Alias('FullName')]
        [string]$Path,

        [Parameter()]
        [string]$OutputPath,

        [Parameter()]
        [switch]$Force
    )

    process {
        $resolvedSource = Resolve-Path -Path $Path -ErrorAction Stop | Select-Object -ExpandProperty Path
        $sourceDir      = Split-Path -Parent $resolvedSource

        if (-not $OutputPath) {
            $base       = [System.IO.Path]::GetFileNameWithoutExtension($resolvedSource)
            $OutputPath = Join-Path $sourceDir "$base.standalone.ps1"
        }

        if ((Test-Path $OutputPath) -and -not $Force) {
            throw "Output file '$OutputPath' already exists. Use -Force to overwrite."
        }

        $sourceContent = Get-Content -Path $resolvedSource -Raw

        # Parse the script using PowerShell's AST so we can locate Import-Module calls
        $errors = @()
        $ast    = [System.Management.Automation.Language.Parser]::ParseInput(
                      $sourceContent, $resolvedSource, [ref]$null, [ref]$errors)

        if ($errors.Count -gt 0) {
            Write-Warning "The source script contains parse errors; results may be incomplete."
        }

        # Find all Import-Module command AST nodes
        $importNodes = $ast.FindAll({
            param($node)
            $node -is [System.Management.Automation.Language.CommandAst] -and
            $node.GetCommandName() -eq 'Import-Module'
        }, $true)

        $inlinedBlocks   = [System.Collections.Generic.List[string]]::new()
        $linesToRemove   = [System.Collections.Generic.HashSet[int]]::new()

        foreach ($node in $importNodes) {
            # The first argument after 'Import-Module' is the module specifier
            $moduleArg = $node.CommandElements | Select-Object -Skip 1 | Select-Object -First 1
            if (-not $moduleArg) { continue }

            $modulePath = $moduleArg.ToString().Trim("'`"")

            # Resolve relative paths relative to the source script's directory
            if (-not [System.IO.Path]::IsPathRooted($modulePath)) {
                $candidate = Join-Path $sourceDir $modulePath
                if (Test-Path $candidate) {
                    $modulePath = $candidate
                }
            }

            $inlineBlock = Get-ModuleFunctionBlock -ModulePath $modulePath -SourceDir $sourceDir
            if ($null -eq $inlineBlock) {
                Write-Verbose "Skipping Import-Module '$modulePath' — module could not be resolved to a local file."
                continue
            }

            $inlinedBlocks.Add($inlineBlock)

            # Mark every line of the Import-Module statement for removal (1-based)
            $startLine = $node.Extent.StartLineNumber
            $endLine   = $node.Extent.EndLineNumber
            for ($l = $startLine; $l -le $endLine; $l++) {
                [void]$linesToRemove.Add($l)
            }
        }

        # Rebuild the script lines, dropping the Import-Module lines
        $lines            = $sourceContent -split "`r?`n"
        $remainingLines   = for ($i = 0; $i -lt $lines.Count; $i++) {
            $lineNum = $i + 1  # AST line numbers are 1-based
            if (-not $linesToRemove.Contains($lineNum)) {
                $lines[$i]
            }
        }

        # Build the output: inlined functions first, then the rest of the script
        $header = @(
            "# This script was generated by Convert-ToStandaloneScript (PwshToolkit).",
            "# Source: $resolvedSource",
            "# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
            ""
        )

        $outputParts = $header

        if ($inlinedBlocks.Count -gt 0) {
            $outputParts += @(
                "#region Inlined module functions",
                ""
            )
            foreach ($block in $inlinedBlocks) {
                $outputParts += $block
                $outputParts += ""
            }
            $outputParts += @(
                "#endregion Inlined module functions",
                ""
            )
        }

        $outputParts += $remainingLines

        $outputContent = $outputParts -join [System.Environment]::NewLine

        if ($PSCmdlet.ShouldProcess($OutputPath, "Write standalone script")) {
            Set-Content -Path $OutputPath -Value $outputContent -Encoding UTF8
            Write-Verbose "Standalone script written to '$OutputPath'."
            Get-Item -Path $OutputPath
        }
    }
}

# ---------------------------------------------------------------------------
# Internal helpers (not exported)
# ---------------------------------------------------------------------------

function Get-ModuleFunctionBlock {
    <#
    .SYNOPSIS
        Returns a string containing all function definitions exported by a module.
    #>
    [OutputType([string])]
    param(
        [string]$ModulePath,
        [string]$SourceDir
    )

    # Resolve .psd1 manifest or .psm1 root module
    $manifestPath = $null
    $rootModulePath = $null

    if ($ModulePath -match '\.psd1$') {
        if (Test-Path $ModulePath) {
            $manifestPath = $ModulePath
        }
    } elseif ($ModulePath -match '\.psm1$') {
        if (Test-Path $ModulePath) {
            $rootModulePath = $ModulePath
        }
    } else {
        # Bare module name — check same directory as source, then module subfolders
        foreach ($ext in @('.psd1', '.psm1')) {
            $candidate = Join-Path $SourceDir "$ModulePath$ext"
            if (Test-Path $candidate) {
                if ($ext -eq '.psd1') { $manifestPath = $candidate } else { $rootModulePath = $candidate }
                break
            }
            # Also try <name>/<name><ext>
            $candidate2 = Join-Path $SourceDir "$ModulePath/$ModulePath$ext"
            if (Test-Path $candidate2) {
                if ($ext -eq '.psd1') { $manifestPath = $candidate2 } else { $rootModulePath = $candidate2 }
                break
            }
        }
    }

    if ($manifestPath) {
        $moduleDir      = Split-Path -Parent $manifestPath
        $manifestData   = Import-PowerShellDataFile -Path $manifestPath -ErrorAction SilentlyContinue
        if ($manifestData -and $manifestData.RootModule) {
            $rootModulePath = Join-Path $moduleDir $manifestData.RootModule
        }
        $exportList = $manifestData.FunctionsToExport
    }

    if (-not $rootModulePath -or -not (Test-Path $rootModulePath)) {
        return $null
    }

    # Collect all .ps1 files dot-sourced from the root module (common pattern)
    $rootModuleDir  = Split-Path -Parent $rootModulePath
    $rootModuleContent = Get-Content -Path $rootModulePath -Raw

    $allContent = [System.Collections.Generic.List[string]]::new()
    $allContent.Add($rootModuleContent)

    # Follow dot-source lines like: . "$PSScriptRoot/Public/Foo.ps1"
    $dotSourcePattern = [regex]'\.\s+[''"]([^''"]+\.ps1)[''"]'
    foreach ($m in $dotSourcePattern.Matches($rootModuleContent)) {
        $relPath   = $m.Groups[1].Value -replace '\$PSScriptRoot', $rootModuleDir
        $relPath   = $relPath -replace '/', [System.IO.Path]::DirectorySeparatorChar
        if (Test-Path $relPath) {
            $allContent.Add((Get-Content -Path $relPath -Raw))
        }
    }

    # Parse the collected content and extract function definitions
    $combinedSource = $allContent -join "`n"
    $ast = [System.Management.Automation.Language.Parser]::ParseInput(
               $combinedSource, [ref]$null, [ref]$null)

    $functionDefs = $ast.FindAll({
        param($n)
        $n -is [System.Management.Automation.Language.FunctionDefinitionAst]
    }, $false)

    if ($functionDefs.Count -eq 0) {
        return $null
    }

    # If we have an export list, filter to only those functions
    if ($exportList -and $exportList.Count -gt 0 -and $exportList -ne '*') {
        $functionDefs = $functionDefs | Where-Object { $_.Name -in $exportList }
    }

    if ($functionDefs.Count -eq 0) {
        return $null
    }

    $blocks = foreach ($fn in $functionDefs) {
        $fn.Extent.Text
    }

    return $blocks -join "`n`n"
}
